config/routes.rb
Watdo::Application.routes.draw do
  match 'signin' => 'sessions#new'
  match 'signup' => 'users#new'
  match 'signout' => 'sessions#destroy'
  resources :users
  resources :sessions
  resources :categories
  resources :tasks

  root :to => 'tasks#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_one :color, foreign_key: :id, primary_key: :color_id
  belongs_to :user

  validates :color_id, presence: true
  validates :user_id, presence: true
  validates :name, presence: true
end

app/models/color.rb
class Color < ActiveRecord::Base
  def to_hex
    output = ""
    [self.red,self.green,self.blue].each do |color|
      hex = color.to_s(16)
      hex = "0"+hex.to_s if (hex.length == 1)
      output += hex
    end
    output
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
  has_one :category, foreign_key: :id, primary_key: :category_id
	validates :description, presence: true
	validates :user_id, presence: true

  def desc_display
    if self.description.length >= 56
      self.description[0..53] + '...'
    else
      self.description
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks
  has_many :categories
  attr_accessible :email, :password, :password_confirmation
  has_secure_password
  validates_presence_of :email, on: :create, message: " can't be blank."
  validates_presence_of :password, on: :create, message: " can't be blank."
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  include ApplicationHelper
  Time.zone = "Pacific Time (US & Canada)"
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # include ApplicationHelper
  before_filter :requires_login, :active_menu_items

  def index
    @category = Category.new
    @categories = @user.categories
    @colors = Color.all

  end

  def new
    @category = Category.new
  end

  def create
    @category = @user.categories.new(params[:category])
    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  def destroy
    @category = @user.categories.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
      format.js
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :active_menu_items
  layout 'welcome'
  def new
    @user = User.new
    @new_user = User.new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_back_or_to tasks_url, notice: "Logged in!"
    else

      if (user)
        alert = "Sorry! Your password doesn't match what we have in our records."
      else
        alert = "Sorry! Your email address doesn't match any in our records!"
      end

      redirect_to new_session_url, alert: alert#"Something went wrong!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include ApplicationHelper
  before_filter :requires_login, :active_menu_items

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = @user.tasks.all
    @task = @user.tasks.new
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = @user.tasks.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = @user.tasks.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = @user.tasks.find(params[:id])
    @categories = []
    @categories.push ['None',-1]
    @user.categories.each do |category|
      @categories.push [category.name,category.id]
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @user.tasks.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    params.delete :category_id if params[:category_id] == -1
    @task = @user.tasks.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = @user.tasks.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :ok }
      format.js
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_back_or_to tasks_url, notice: 'Signed up!'
    else
      redirect_to new_session_url, alert: @user.errors.full_messages.first
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'welcome'
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_menu_items
    #params[:controller] == 'tasks'
    #params[:action] == 'index'
    case params[:controller]
    when 'tasks'
      @tasks_active = true
    when 'categories'
      @account_active = true
    when 'sessions'
      @signup_active = true
    when 'schmerp'
      @help_active = true
    end
  end
  def item_active(item)
    if item.nil?
      "<li>"
    else
      "<li class=\"active\">"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]
      @user ||= User.find_by_id(session[:user_id])
    else
      nil
    end
  end

  def signed_in?
    !(current_user.nil?)
  end

  def requires_login
    if (!signed_in?) #If user is signed out
      session[:url] = request.url
      redirect_to signin_url, notice: request.path == '/' ?  nil : "Must be logged in to view this page!"
      # redirect_to signin_url, notice: "Must be logged in to view this page!"
    else
      current_user
    end
  end

  # Thanks sorcery.
  #
  # used when a user tries to access a page while logged out, is asked to login,
  # and we want to return him back to the page he originally wanted.
  def redirect_back_or_to(url, flash_hash = {})
    redirect_to(session[:url] || url, :flash => flash_hash)
    session[:url] = nil
  end

  def signin_signout_url
    if signed_in?
      return ['Log Out', signout_url]
    else
      ['Log In', signin_url]
    end
  end
  #helper_method :current_user, :signed_in?, :requires_login, :redirect_back_or_to
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_category.html.erb
<li>
Name: <%= category.name %> color: <%= category.color.name %> <%= link_to '✗', category, class: 'btn btn-danger', method: :delete %>
</li>

app/views/categories/_color.html.erb
<%= content_tag :div, style: "background-color: ##{color.to_hex}" do -%>
<%= color.name %>
<% end %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, class: 'span3', placeholder: 'School' %>
    <%= f.select :color_id, options_from_collection_for_select(@colors, "id", "name") %>
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/index.html.erb
<h2>Categories</h2>
<div class="alert alert-info" id="errors"></div>
<%= render 'form' %>
<ul>
<%= render @categories %>
</ul>
<div id="legend">
  <h2>Legend</h2>
<%= render partial: 'categories/color', collection: @colors %>
</div>

app/views/layouts/_login.html.erb
<!-- Nav bar -->
<nav class="group">
  <!-- Logo -->
  <h1 class="brand"><%= link_to "wat.do", root_url%></h1>
  <%= form_tag sessions_url, :class => "well form-inline pull-right" do %>

    <%= text_field_tag :email, params[:email], class: 'input-small', size: nil, placeholder: "Email" %>
    <%= password_field_tag :password, nil, class: 'input-small', size: nil, placeholder: 'Password' %>
    <%= submit_tag "Log in", class: "btn btn-primary" %>
    <% end %>
  </form>
</nav>

app/views/layouts/_menu.html.erb
<!-- Nav bar -->
<nav class="group">
	<!-- Logo -->
	<h1 class="brand"><%= link_to "wat.do", root_url%></h1>
	<% @signout = signin_signout_url %>
	<ul class="nav nav-pills pull-right">
		<!--  Continue as they passed links -->
		<%= item_active(@tasks_active).html_safe %><%= link_to "Tasks", tasks_url %></li>
		<%= item_active(@account_active).html_safe%><%= link_to "Categories", categories_url %></li>
		<%= item_active(@help_active).html_safe%><%= link_to "Help", '#' %></li>

		<%= item_active(@signup_active).html_safe%><%= link_to @signout[0], @signout[1]%></li>
	</ul>


</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>wat.do</title>
	<link href='http://fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>
<div class="topspacing"></div>
<%= render partial: 'layouts/menu' %>
<div class="container">
  <div class="hero-unit">

    <% if flash[:notice] %>
      <div class="alert alert-info"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-error"><%= flash[:alert] %></div>
    <% end %>

    <%= yield %>

  </div>
</div>
</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>wat.do</title>
	<link href='http://fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>
<div class="topspacing"></div>
<%= render partial: 'layouts/login' %>
<div class="container">
  <div class="hero-unit">
    
    <% if flash[:notice] %>
      <div class="alert alert-info"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-error"><%= flash[:alert] %></div>
    <% end %>

    <%= yield %>
  
  </div>
</div>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :description %>
    <%= f.select :category_id, @categories %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_miniform.html.erb
<%= form_for(@task, remote: true) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p id="task-input-helper">Press enter to add a task</p>
    <%= f.text_field :description, class: 'span3', placeholder: 'Walk the dog' %>

  </div>
<% end %>

app/views/tasks/_task.html.erb
<% style = (task.category != nil && task.category.color != nil) ? "background-color: ##{task.category.color.to_hex}" : nil %>
<%= content_tag :li, id: task.id, style: style do -%>

    <%= best_in_place task, :description, type: 'input', display_as: :desc_display %>
    <!-- <i class="icon-pencil"></i> -->
    <%= link_to 'Edit', edit_task_path(task), class: 'btn left-more task-done' %>
    <%= link_to '✔', task, class: 'btn btn-success task-done', method: :delete, remote: true %>
<% end -%>

app/views/tasks/_test_a.html.erb
<%= form_for(@task, remote: true) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="input-append">
      <button id="btn-description" class="btn active" type="button" style="margin-right: -7px;">
        <div style="font-size: 24px;"><i class="icon-edit"></i></div>
      </button>

      <%= f.text_field :description, placeholder: 'Walk the dog' %>

      <button id="btn-date" class="btn" type="button" style="margin-right: -5px;">
        <div style="font-size: 24px;"><i class="icon-time"></i></div>
      </button>
      <%= f.text_field :date, placeholder: 'Tuesday at 1 pm' %>

      <button id="btn-place" class="btn" type="button" style="margin-right: -6px;">
        <div style="font-size: 24px;"><i class="icon-home"></i></div>
      </button>
      <%= f.text_field :place, placeholder: 'Dog Park' %>

    </div>
    
    
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<div class="alert alert-info" id="errors"></div>
<%= render 'miniform' %>
<div class="note-box">
  <!-- <thead>
    <th>Description</th>
    <th></th>
  </thead> -->
<div class="white">
<ul>
<%= render @tasks %>
</ul>
</div>
</div>
<br />

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>User:</b>
  <%= @task.user_id %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/welcome/index.html.erb
<div class="row">
	<div class="billboard">
		<img src="http://placehold.it/490x410&text=Fancy+Screenshot+Here">

	</div>

	<div id="register-form" class="span4">
		<%= form_for @user, class: "well" do |f| %>
		<form class="well">
		  <h2>New to wat.do?</h2>
		  <%= f.text_field :email,placeholder: "Email" %>
		  <%= f.password_field :password, placeholder: "Password" %>
		  <%= f.password_field :password_confirmation, placeholder: "Password Confirmation" %>
		  <%= submit_tag "Create Account", size: nil, class: "btn btn-primary" %>
		<% end %>
	</div>
	<div class="well" id="reasons">
		<h2>Why join?</h2>
		<ul>
			<li><p>We won't get in your way.</p></li>
			<li><p>Our domain name is awesome.</p></li>
		</ul>
	</div>
</div>